#!/bin/bash
. /var/openpanel/api/sh/module.sh

MysqlAdmin.update() {
  appid=mysql
  newpass=$(coreval MysqlAdmin password)
  method=$(coreval MysqlAdmin backupmethod)
  [ ! -z ${newpass} ] &&  authd runscript openapp-call "$appid" passwd "$newpass"
  [ -x /usr/bin/openapp-mysql-backupmethod ] && authd runscript openapp-call "$appid" backupmethod "$method"
}

Module.getconfig() {
METHOD=mysqldump

CHECKLOC=/etc/openapp-backup/scripts.d/xtrabackup
[ -L ${CHECKLOC} -o -f ${CHECKLOC} ] && METHOD=xtrabackup

  cat << _EOF_
  <openpanel.module>
    <dict id="MysqlAdmin" type="class">
      <dict id="openapp-mysql-settings" type="object">
	    <enum id="backupmethod">${METHOD}</enum>
      </dict>
    </dict>
	<dict id="OpenCORE:Result">
      <integer id="error">0</integer>
      <string id="message">OK</string>
    </dict>
  </openpanel.module>
_EOF_
  exitquiet
}

implement OpenAppMysql.module
